name: build
on: [ pull_request, push ]

jobs:
  build:
    strategy:
      matrix:
        java: [ 25 ]
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v6
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: setup gradle
        uses: gradle/actions/setup-gradle@v6
      - name: Chmod gradlew
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
      - name: Upload Artifacts
        if: ${{ runner.os == 'Linux'}}
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: |
            build/libs/*.jar
            !build/libs/*-sources.jar
          archive: false
